service-site/service-site/Models/ErrorViewModel.cs
using System;

namespace service_site.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

service-site/service-site/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using service_site.Models;

namespace service_site.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

service-site/service-site/Controllers/ElementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace service_site.Controllers
{
    public class ElementsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

service-site/service-site/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using service_site.Models;

namespace service_site.Controllers
{
    public class ProjectsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

service-site/service-site/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using service_site.Models;

namespace service_site.Controllers
{
    public class ServiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

service-site/service-site/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using service_site.Models;

namespace service_site.Controllers
{
    public class SiteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

service-site/service-site/Views/About/Index.cshtml
<!-- start banner Area -->
<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    About
                </h1>
                <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="services.html"> About</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->	

service-site/service-site/Views/Projects/Index.cshtml
<!-- start banner Area -->
<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Projects
                </h1>
                <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="services.html"> Projects</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->	

service-site/service-site/Views/Service/Index.cshtml
<!-- start banner Area -->
<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Наши услуги
                </h1>
                <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="services.html"> Service</a></p>
            </div>
        </div>
    </div>
</section>
<!-- End banner Area -->	

service-site/service-site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/favicon.ico">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">

    <title> title </title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">

    <link rel="stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/hexagons.min.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/main.css">
</head>
<body>
    <header id="header" id="home">
        <div class="header-top slider">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-sm-12 col-12 header-top-right no-padding">
                        <a class="fa fa-map-marker text-light" asp-controller="about" asp-action="index"> Тула, ул. Демонстрации, 40</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo">
                    <a class="nav-link text-dark logo" asp-controller="Site" asp-action="Index"><img src="img/logo.png" width="142" height="40" alt="" title="" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li class="menu-active"><a class="nav-link text-dark" asp-controller="Site" asp-action="Index">Главная</a></li>
                        <li><a class="nav-link text-dark" asp-controller="about" asp-action="index">О Компании</a></li>
                        <li><a class="nav-link text-dark" asp-controller="service" asp-action="index">Услуги</a></li>
                        <li><a class="nav-link text-dark">Прайс</a></li>
                        <li class="menu-has-children">
                            <a class=" nav-link text-dark" asp-controller="Elements" asp-action="Index">Elements</a>
                            <ul>
                                <li><a class="nav-link text-dark" asp-controller="Blog" asp-action="Home">123</a></li>
                                <li><a class="nav-link text-dark" asp-controller="Blog" asp-action="Single">456</a></li>
                            </ul>
                        </li>
                        <li class="menu-has-children">
                            <a class="nav-link text-dark" asp-controller="Blog" asp-action="Index">Blog</a>
                            <ul>
                                <li><a class="nav-link text-dark" asp-controller="Blog" asp-action="Home">Blog-Home</a></li>
                                <li><a class="nav-link text-dark" asp-controller="Blog" asp-action="Single">Blog-Single</a></li>
                            </ul>
                        </li>
                        <!--li><a class="nav-link text-dark" asp-controller="Contact" asp-action="Index">Contact</a></li-->
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <!-- #header -->

    @RenderBody()

    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Us</h6>
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.
                        </p>
                        <p class="footer-text">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright @DateTime.Now.Year &copy;
                            All rights reserved <br /> This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
                <div class="col-lg-5  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>Stay update with our latest</p>
                        <div class="" id="mc_embed_signup">
                            <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">
                                <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
                                <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                <div style="position: absolute; left: -5000px;">
                                    <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                </div>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                    <div class="single-footer-widget">
                        <h6>Follow Us</h6>
                        <p>Let us be social</p>
                        <div class="footer-social d-flex align-items-center">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/hexagons.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>

service-site/service-site/Views/Site/About.cshtml
<section class="banner-area relative" id="home">
    <div class="overlay overlay-bg"></div>
    <div class="container">
        <div class="row fullscreen d-flex align-items-center justify-content-center">
            <div class="banner-content col-lg-12 col-md-12">
                <h1>
                    About
                </h1>
                <a href="#" class="primary-btn header-btn text-uppercase">Get Started</a>
            </div>
        </div>
    </div>
</section>